---
apiVersion: v1
kind: Service
metadata:
  name: lab2
spec:
  type: LoadBalancer
  selector:
    app: lab2
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2
  labels:
    app: lab2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab2
  template:
    metadata:
      labels:
        app: lab2
    spec:
      containers:
        - name: lab2
          image: us-east1-docker.pkg.dev/arquitectura-437622/repository/lab2:latest